- repo: git://github.com/anmolnagpal/git-hooks-terraform
  rev: v1.0.0 # Use the ref you want to point at
  hooks:
  - id: fmt
  - id: validate
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v3.3.0 # Use the ref you want to point at
  hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-byte-order-marker
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-yaml
      - id: check-added-large-files
